# DataSource settings

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/test1}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# VNPAY Config
vnpay.tmn.code=${VNPAY_TMN_CODE:vnpay_tmn_code_local}
vnpay.secret.key=${VNPAY_SECRET_KEY:vnpay_secret_key_local_xxxxxxxxxxxxxxxxxx}

# JWT Config
mathcha_edu.jwt.base64-secret=${JWT_SECRET_KEY:chuoi_bi_mat_gia_de_test_local_1234567890qwertyuiopasdfghjklzxcvbnmqwertyuiop}
#expiration: 1 day (seconds 24*60*60)
#100 days
mathcha_edu.jwt.token-validity-in-seconds=8640000
#
###